### ISSUE TITLE
Multiple value typos in the .env file

### ISSUE THREAD

**Issue by Jbziscool** [bchurton/cw-modmail#1]
Typo in environment variable name: "MONGO_UR" should be "MONGO_URL" in the environment file.

Missing environment variable: "LOGS" seems to be referenced in the code, but it is not defined in the environment file.

Typo in environment variable name: "ERROR_LOGS_WEBHOOK" should be "ERROR_LOG_WEBHOOK" in the environment file.

Typo in environment variable name: "ERROR_LOGS_THREAD" should be "LOG_THREAD" in the environment file.

here is the .env/.env.example file with the correct values

MONGO_URL=
MONGO_DB=
TOKEN=

GUILD=
CATEGORY=
LOGS=

PING_ROLES=

STATUS=DM me for help!

PREFIX=!

ERROR_LOG_WEBHOOK=
LOG_THREAD=

SUCCESS_EMOJI=✅
ERROR_EMOJI=❌

**Comment by dev-bun** [comment]
My god I can't spell 😭

**Comment by Jbziscool** [comment]
lmfao

> My god I can't spell 😭

**Comment by dev-bun** [comment]
fixed in #2
